services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: globodb
      MYSQL_USER: arpit
      MYSQL_PASSWORD: arpit
    ports:
      - 3306:3306 
    volumes:
      - ./mysql:/var/lib/mysql

  redis:
    image: redis
    restart: always
    command: ["redis-server", "--requirepass", "arpit"]
    ports:
      - 6379:6379

  redisinsight:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - 5540:5540
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=arpit
    depends_on:
      - redis
