version: '3.7'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 898531
      MYSQL_DATABASE: globodb
      MYSQL_USER: arpit
      MYSQL_PASSWORD: arpit
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"

 

